routes/auth_routes.py
# auth_routes.py
import datetime

from flask import Blueprint, redirect, url_for, render_template, session, request, flash
from flask_bcrypt import Bcrypt
from flask_pymongo import PyMongo

from forms.forms import LoginForm, RegistrationForm

# Create instances of Flask extensions
mongo = PyMongo()
bcrypt = Bcrypt()
# Create a Blueprint named 'auth'
auth_blueprint = Blueprint('auth', __name__)


# Route for user login
@auth_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    error_message = None
    success_message = request.args.get('success_message')  # bring the message from the request for registration success

    if form.validate_on_submit():
        # If the form is submitted and valid
        username = form.username.data
        password = form.password.data

        # Query the database to find the user by username
        user = mongo.db.users.find_one({'username': username})

        # Check if the user exists and the password matches the hashed password
        if user and bcrypt.check_password_hash(user['password'], password):
            success_message = 'Login eseguito con successo!'
            session['username'] = username  # Store the username in the session for tracking authentication
            session['success_message'] = success_message
            return redirect(url_for('tweets.timeline'))  # Redirect to the user's timeline after successful login
        else:
            error_message = 'Credenziali non valide. Riprova.'

    return render_template('login.html', form=form, error_message=error_message, success_message=success_message)


# Route for user registration
@auth_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()

    try:
        if form.validate_on_submit():
            # If the form is submitted and valid
            first_name = form.first_name.data
            last_name = form.last_name.data
            email = form.email.data
            username = form.username.data
            password = form.password.data
            birth_date_str = form.birth_date.data

            if birth_date_str:
                # Convert date from string to datetime.date object
                birth_date = datetime.datetime.strptime(birth_date_str, '%d-%m-%Y').date()

                # Check if there is already a user with the same email or username
                existing_user = mongo.db.users.find_one({"$or": [{"email": email}, {"username": username}]})
                if existing_user:
                    flash('Email o nome utente già in uso. Scegliere un altro.', 'danger')
                    return render_template('register.html', form=form)

                # Generate hashed password for security
                hashed_password = bcrypt.generate_password_hash(password).decode('utf-8')

                # Continue with user registration by inserting data into the database
                mongo.db.users.insert_one({
                    'first_name': first_name,
                    'last_name': last_name,
                    'email': email,
                    'username': username,
                    'password': hashed_password,
                    'birth_date': birth_date.strftime('%Y-%m-%d')
                })

                return redirect(url_for('auth.login',
                                        success_message='Registrazione completata con successo! Ora puoi effettuare '
                                                        'il login'))
    except Exception as e:
        print(e)

    return render_template('register.html', form=form)


# Route for user logout
@auth_blueprint.route('/logout')
def logout():
    # Clear all data stored in the session
    session.clear()
    # Redirect the user to the login page (or home page)
    return redirect(url_for('auth.login'))

routes/tweet_routes.py
from bson import ObjectId
from flask import Blueprint, redirect, url_for, render_template, session

from forms.forms import TweetForm, SearchForm
from routes.auth_routes import mongo
from utils import (update_trending_hashtags, insert_tweet)  # Assicurati che il nome dell'app sia corretto

tweet_blueprint = Blueprint('tweets', __name__)


@tweet_blueprint.route('/timeline', methods=['GET', 'POST'])
def timeline():
    if 'username' not in session:
        return redirect(url_for('auth.login'))

    success_message = session.pop('success_message', None)

    # Retrieve the users you are following
    user = mongo.db.users.find_one({'username': session['username']})
    following = user.get('following', [])

    # Retrieve tweets of the current user and those they are following
    user_tweets = mongo.db.tweets.find({'username': {'$in': [session['username']] + following}})

    tweet_form = TweetForm()

    search_form = SearchForm()

    good_message = None

    bad_message = None

    # Retrieve trending hashtags
    trending_hashtags = update_trending_hashtags()

    if search_form.validate_on_submit():
        search_query = search_form.search_query.data
        # Execute the logic to search for users in the database
        search_results = list(mongo.db.users.find({
            'username': {'$regex': f'.*{search_query}.*', '$options': 'i'}
        }))

        # If there is exactly one result in the search, redirect directly to the user's profile
        if len(search_results) == 1:
            return redirect(url_for('user_profile.view_profile', username=search_results[0]['username']))
        elif not search_results:
            bad_message = 'Nessun Profilo Trovato !'

    if tweet_form.validate_on_submit():
        good_message = insert_tweet(session['username'], tweet_form.tweet_content.data)

        if good_message:
            return redirect(url_for('tweets.timeline'))

        # Now retrieve trending hashtags again
        trending_hashtags = update_trending_hashtags()

    return render_template('timeline.html', tweets=user_tweets,
                           tweet_form=tweet_form, success_message=success_message,
                           good_message=good_message, trending_hashtags=trending_hashtags,
                           search_form=search_form, bad_message=bad_message)


@tweet_blueprint.route('/repeat_tweet/<page>/<tweet_id>', methods=['POST'])
def repeat_tweet(page, tweet_id):
    if 'username' not in session:
        return redirect(url_for('auth.login'))

    # Get the current tweet from the database
    tweet = mongo.db.tweets.find_one({'_id': ObjectId(tweet_id)})

    # Increment the retweet count
    mongo.db.tweets.update_one({'_id': ObjectId(tweet_id)}, {'$inc': {'retweets': 1}})

    # Redirect based on the page (timeline or profile)
    if page == 'tweets.timeline':
        return redirect(url_for('tweets.timeline'))
    elif page == 'profile':
        return redirect(url_for('user_profile.profile'))
    else:
        # Unknown page, handle as preferred
        return redirect(url_for('user_profile.view_profile', username=tweet['username']))


@tweet_blueprint.route('/like_tweet/<page>/<tweet_id>', methods=['POST'])
def like_tweet(page, tweet_id):
    if 'username' not in session:
        return redirect(url_for('auth.login'))

    # Get the current tweet from the database
    tweet = mongo.db.tweets.find_one({'_id': ObjectId(tweet_id)})

    # Check if the user has already liked the tweet
    if session['username'] in tweet['likes']:
        # if yes, remove the like
        mongo.db.tweets.update_one({'_id': ObjectId(tweet_id)},
                                   {'$pull': {'likes': session['username']}})
    else:
        # if no, add the like
        mongo.db.tweets.update_one({'_id': ObjectId(tweet_id)},
                                   {'$push': {'likes': session['username']}})

    # Redirect based on the page (timeline or profile)
    if page == 'tweets.timeline':
        return redirect(url_for('tweets.timeline'))
    elif page == 'profile':
        return redirect(url_for('user_profile.profile'))
    else:
        return redirect(url_for('user_profile.view_profile', username=tweet['username']))


@tweet_blueprint.route('/hashtag/<hashtag>', methods=['GET'])
def hashtag_tweets(hashtag):
    if 'username' not in session:
        return redirect(url_for('auth.login'))

    # Retrieve all tweets containing the specified hashtag (case-insensitive)
    hashtag_tweetss = list(mongo.db.tweets.find({'hashtags': {'$regex': f'^{hashtag}$', '$options': 'i'}}))

    return render_template('hashtag_tweets.html', hashtag_tweets=hashtag_tweetss,
                           hashtag=hashtag)

routes/user_profile_routes.py
import os

from flask import Blueprint, render_template, url_for, session
from werkzeug.utils import redirect

from forms.forms import FollowForm, TweetForm, UnfollowForm, ProfileImageForm
from routes.auth_routes import mongo
from utils import get_profile_image_path, insert_tweet

user_profile_blueprint = Blueprint('user_profile', __name__)


@user_profile_blueprint.route('/profile', methods=['GET', 'POST'])
def profile():
    if 'username' not in session:
        return redirect(url_for('auth.login'))

    user_tweets = list(mongo.db.tweets.find({'username': session['username']}))
    user = mongo.db.users.find_one({'username': session['username']})
    following = user.get('following', [])
    follow_form = FollowForm()
    tweet_form = TweetForm()
    unfollow_form = UnfollowForm()
    profile_image_form = ProfileImageForm()

    good_message = None
    warning_message = None
    danger_message = None

    if tweet_form.validate_on_submit():
        good_message = insert_tweet(session['username'], tweet_form.tweet_content.data)

        if good_message:
            return redirect(url_for('user_profile.profile'))

    if unfollow_form.validate_on_submit():
        unfollow_username = unfollow_form.unfollow_username.data

        if unfollow_username == session['username']:
            danger_message = 'Non puoi smettere di seguire te stesso.'
        elif unfollow_username not in following:
            warning_message = f'Non stai seguendo {unfollow_username}.'
        else:
            mongo.db.users.update_one({'username': session['username']},
                                      {'$pull': {'following': unfollow_username}})
            mongo.db.users.update_one({'username': unfollow_username},
                                      {'$pull': {'followers': session['username']}})
            good_message = f'Hai smesso di seguire {unfollow_username}.'

    if follow_form.validate_on_submit():
        follow_username = follow_form.follow_username.data
        user_to_follow = mongo.db.users.find_one({'username': follow_username})

        if user_to_follow and follow_username != session['username']:
            if follow_username not in following:
                mongo.db.users.update_one({'username': session['username']},
                                          {'$push': {'following': follow_username}})
                mongo.db.users.update_one({'username': follow_username},
                                          {'$push': {'followers': session['username']}})
                good_message = f'Hai iniziato a seguire {follow_username}.'

            else:
                warning_message = f'Hai già seguito {follow_username}.'
        elif follow_username == session['username']:
            danger_message = 'Non puoi seguire te stesso.'
        else:
            danger_message = f'L\'utente {follow_username} non esiste.'

    user = mongo.db.users.find_one({'username': session['username']})
    updated_following = list(user.get('following', []))
    updated_followers = list(user.get('followers', []))

    # Update image choices for the profile image form with images from the specified folder
    images_folder = 'static/profile_images'  # Replace with the actual path to your folder
    image_choices = [(image, image) for image in os.listdir(images_folder) if image.endswith(('.jpg', '.jpeg', '.png'))]
    profile_image_form.image_choice.choices = image_choices

    if profile_image_form.validate_on_submit():
        # Get the user selected file name
        selected_image = profile_image_form.image_choice.data

        # check if the user has selected an image
        if selected_image:
            # Update the image path in the database with the selected image name.
            mongo.db.users.update_one({'username': session['username']},
                                      {'$set': {'profile_image_path': selected_image}})

    # Assign the profile image path directly to the variable
    profile_image_path = get_profile_image_path(session['username'])

    return render_template('profile.html', tweets=user_tweets, following=updated_following,
                           followers=updated_followers,
                           profile_image_path=profile_image_path,
                           follow_form=follow_form, tweet_form=tweet_form,
                           unfollow_form=unfollow_form,
                           profile_image_form=profile_image_form,
                           good_message=good_message, warning_message=warning_message, danger_message=danger_message)


@user_profile_blueprint.route('/followers/<username>')
def followers(username):
    # Retrieve the list of followers for the user specified by the 'username' parameter.
    user = mongo.db.users.find_one({'username': username})

    if user is None:
        # user not found
        return render_template('login.html')

    followers_list = user.get('followers', [])
    return render_template('followers.html', followers_list=followers_list, username=username)


@user_profile_blueprint.route('/following/<username>')
def get_following(username):
    # Retrieve the list of following for the user specified by the 'username' parameter.
    user = mongo.db.users.find_one({'username': username})

    if user is None:
        # user not found
        return render_template('login.html')

    following_list = user.get('following', [])
    return render_template('following.html', following_list=following_list, username=username)


@user_profile_blueprint.route('/view_profile/<username>')
def view_profile(username):
    # Check if the user is authenticated
    if 'username' not in session:
        return redirect(url_for('auth.login'))

    # Retrieve the user from the session.
    current_user = mongo.db.users.find_one({'username': session['username']})

    # Retrieve the viewed profile user
    user = mongo.db.users.find_one({'username': username})

    # Retrieve the tweets of the viewed profile user
    user_tweets = list(mongo.db.tweets.find({'username': username}))

    # Retrieve the followers and following lists of the viewed profile user
    followers_list = user.get('followers', [])
    following_list = user.get('following', [])

    # Check if the session user is trying to view their own profile
    if current_user and current_user['username'] == user['username']:
        # The session user is trying to view their own profile
        return redirect(url_for('user_profile.profile'))

    else:
        # The session user is trying to view the profile of another user.
        return render_template('user_profile.html', user=user, tweets=user_tweets, followers=followers_list,
                               following=following_list)

templates/profile.html
{% extends 'layout.html' %}
{% block content %}
    <title>Profile</title>
    <script src="/static/profile.js"></script>
    <link rel="stylesheet" href="/static/timeline.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossorigin="anonymous">

    <link rel="stylesheet" href="/static/profile.css">


                <div class="container-fluid">
                    <div class="row">
                        <!-- sidebar starts -->
                        <div class="sidebar">
                <i class="fab fa-twitter"></i>
                <div class="sidebarOption {% if request.endpoint == 'tweets.timeline' %} active {% endif %}" onclick="window.location.href='{{ url_for('tweets.timeline') }}'">
                    <span class="material-icons">home</span>
                    <h2>Home</h2>
                </div>
                <div class="sidebarOption {% if request.endpoint == 'user_profile.profile' %} active {% endif %}" onclick="window.location.href='{{ url_for('user_profile.profile') }}'">
                    <span class="material-icons">perm_identity</span>
                    <h2>Profile</h2>
                </div>
                <div class="sidebarOption" onclick="window.location.href='{{ url_for('auth.logout') }}'">
                    <span class="material-icons">exit_to_app</span>
                    <h2>Logout</h2>
                </div>
            </div>
                        <!-- sidebar ends -->
            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="container">
                    <div class="col-lg-8">
                        {% if good_message %}
                            <div class="notify" role="alert">
                                {{ good_message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                            </div>
                        {% elif warning_message %}
                            <div class="notify" role="alert">
                                {{ warning_message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                            </div>
                        {% elif danger_message %}
                            <div class="notify" role="alert">
                                {{ danger_message }}
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                            </div>
                        {% endif %}
                        <div class="panel profile-cover">
                            <div class="profile-cover__img">
                                <img src="{{ profile_image_path }}" alt="">
                                <h3 class="h3">{{ session['username'] }}</h3>
                            </div>
                            <div class="profile-cover__action bg--img" data-overlay="0.3">
                                <form id="followForm" method="post" action="/user_profile/profile">
                                    {{ follow_form.csrf_token }}
                                    <label for="{{ follow_form.follow_username.id }}">{{ follow_form.follow_username.label }}</label>
                                    {{ follow_form.follow_username(size=15, placeholder='Username', class='form-control') }}
                                    <input type="hidden" name="action" value="follow">
                                    {{ follow_form.submit(class='btn btn-rounded btn-info') }}
                                </form>

                                <form id="unfollowForm" class="second-form" method="post"
                                      action="/user_profile/profile">
                                    {{ unfollow_form.csrf_token }}
                                    <label for="{{ unfollow_form.unfollow_username.id }}">{{ unfollow_form.unfollow_username.label }}</label>
                                    {{ unfollow_form.unfollow_username(size=15, placeholder='Username', class='form-control') }}

                                    <input type="hidden" name="action" value="unfollow">
                                    {{ unfollow_form.submit(class='btn btn-rounded btn-info') }}
                                </form>
                            </div>

                            <div class="profile-cover__info">
                                <ul class="nav">
                                    <li>{{ tweets|length }} Tweet</li>
                                    <li>{{ followers|length }} <a
                                            href="{{ url_for('user_profile.followers', username=session['username']) }}">follower</a>
                                    </li>
                                    <li>{{ following|length }} <a
                                            href="{{ url_for('user_profile.get_following', username=session['username']) }}">seguiti</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <!-- Aggiungi questa sezione per il caricamento dell'immagine del profilo -->
                        <div class="profile-image-upload">
                            <form method="post" action="{{ url_for('user_profile.profile') }}" enctype="multipart/form-data">
                                {{ profile_image_form.csrf_token }}
                                <!-- Utilizza il nuovo campo di selezione image_choice -->
                                <div class="mb-3">
                                    <label for="profile-image" class="form-label">Choose Profile Image</label>
                                    {{ profile_image_form.image_choice(id='profile-image', class='form-control') }}
                                </div>
                                <!-- Mantieni il pulsante di invio -->
                                <button type="submit" class="btn btn-primary custom-upload-button">Upload</button>
                            </form>
                        </div>

                        <div class="panel">
                            <hr class="gray-line">
                            <!-- tweetbox starts -->
                            <div class="tweetBox">
                                <form method="post" action="{{ url_for('user_profile.profile') }}">
                                    {{ tweet_form.csrf_token }}
                                    <div class="tweetbox__input">
                                        {{ tweet_form.tweet_content(cols=50, rows=5, placeholder="What's happening?", class='form-control invisible-borders') }}
                                    </div>
                                    <button class="tweetBox__tweetButton" type="submit">Tweet</button>
                                </form>
                            </div>
                            <!-- tweetbox ends -->
                            <p></p>
                            <p></p>
                            <ul class="panel-activity__list">
                                {% for tweet in tweets | reverse %}
                                    <div class="post">
                                    <li>
                                        <div class="activity__list__header">
                                            <img src="{{ profile_image_path }}" alt=""/>
                                            <strong>{{ tweet.username }}</strong> posted the tweet :
                                             <span class="clock" > <i class="fas fa-clock me-1" > </i> {{ tweet.timestamp.strftime('%d-%m-%Y %H:%M') }}</span>
                                        </div>
                                        <div class="activity__list__body entry-content">
                                            <p>{{ tweet.content }}</p>

                                        </div>
                                        <div class="button-container">
                                            <form method="post"
                                                  action="{{ url_for('tweets.repeat_tweet', page='profile', tweet_id=tweet._id) }}">
                                                <button type="submit" class="repeat-button"
                                                        id="repeat-btn-{{ tweet._id }}">
                                                    <span class="material-icons">repeat</span>
                                                    <span class="repeat-count">{{ tweet.retweets }}</span>
                                                </button>
                                            </form>
                                            <form method="post"
                                                  action="{{ url_for('tweets.like_tweet', page='profile', tweet_id=tweet._id) }}">
                                                <button type="submit"
                                                        class="like-button {% if session['username'] in tweet['likes'] %}active{% endif %}"
                                                        id="like-btn-{{ tweet._id }}">
                                                    <span class="material-icons">favorite_border</span>
                                                    <span class="like-count">{{ tweet.likes | length }}</span>
                                                </button>
                                            </form>
                                        </div>
                                    </li>
                                    </div>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>

{% endblock %}

templates/user_profile.html
<!-- user_profile.html -->
{% extends 'layout.html' %}
{% block content %}
    <title>{{ user.username }} - Profile</title>
    <link rel="stylesheet" href="/static/timeline.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
          integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
          crossorigin="anonymous">

    <link rel="stylesheet" href="/static/profile.css">
    <link rel="stylesheet" href="/static/user_profile.css">
    <div class="container-fluid">
        <div class="row">
            <!-- sidebar starts -->
            <div class="sidebar">
                <i class="fab fa-twitter"></i>
                <div class="sidebarOption {% if request.endpoint == 'tweets.timeline' %} active {% endif %}" onclick="window.location.href='{{ url_for('tweets.timeline') }}'">
                    <span class="material-icons">home</span>
                    <h2>Home</h2>
                </div>
                <div class="sidebarOption {% if request.endpoint == 'user_profile.profile' %} active {% endif %}" onclick="window.location.href='{{ url_for('user_profile.profile') }}'">
                    <span class="material-icons">perm_identity</span>
                    <h2>Profile</h2>
                </div>
                <div class="sidebarOption" onclick="window.location.href='{{ url_for('auth.logout') }}'">
                    <span class="material-icons">exit_to_app</span>
                    <h2>Logout</h2>
                </div>
            </div>
            <!-- sidebar ends -->

            <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                <div class="container">
                    <div class="col-lg-8">
                        <!-- Sezione del profilo dell'utente -->
                        <div class="panel profile-cover">
                            <div class="profile-cover__img">
                                <img src="{{ get_profile_image_path(user.username) }}" alt="">
                                <h3 class="h3">{{ user.username }}</h3>
                            </div>
                            <br><br><br><br><br><br><br><br>
                            <div class="profile-cover__info">
                                <ul class="nav">
                                    <li>{{ tweets|length }} Tweet</li>
                                    <li>{{ followers|length }} <a href="{{ url_for('user_profile.followers', username=user.username) }}">followers</a></li>
                                    <li>{{ following|length }} <a href="{{ url_for('user_profile.get_following', username=user.username) }}">seguiti</a></li>
                                </ul>
                            </div>
                        </div>
                        <!-- Fine della sezione del profilo dell'utente -->
                            <br>
                        <!-- Sezione per visualizzare i tweet -->
                        <div class="panel">
                            <hr class="gray-line">
                            <ul class="panel-activity__list">
                                {% for tweet in tweets | reverse %}
                                    <div class="post">
                                        <li>
                                            <div class="activity__list__header">
                                                    <img src="{{ get_profile_image_path(user.username) }}" alt="">
                                                <strong>{{ tweet.username }}</strong> posted the tweet :
                                                <span class="date_" > <i class="fas fa-clock me-1" > </i> {{ tweet.timestamp.strftime('%d-%m-%Y %H:%M') }}</span>
                                            </div>
                                            <div class="activity__list__body entry-content">
                                                <p>{{ tweet.content }}</p>
                                            </div>
                                     <div class="button-container">
                                        <form method="post"
                                              action="{{ url_for('tweets.repeat_tweet', page='user_profile.view_profile', tweet_id=tweet._id) }}">
                                            <button type="submit" class="repeat-button"
                                                    id="repeat-btn-{{ tweet._id }}">
                                                <span class="material-icons">repeat</span>
                                                <span class="repeat-count">{{ tweet.retweets }}</span>
                                            </button>
                                        </form>
                                        <form method="post"
                                              action="{{ url_for('tweets.like_tweet', page='user_profile.view_profile', tweet_id=tweet._id) }}">
                                            <button type="submit"
                                                    class="like-button {% if session['username'] in tweet['likes'] %}active{% endif %}"
                                                    id="like-btn-{{ tweet._id }}">
                                                <span class="material-icons">favorite_border</span>
                                                <span class="like-count">{{ tweet.likes | length }}</span>
                                            </button>
                                        </form>
                                    </div>

                                        </li>
                                    </div>
                                {% endfor %}
                            </ul>
                        </div>
                        <!-- Fine della sezione per visualizzare i tweet -->
                        <!-- Altri contenuti della pagina, se necessario -->
                    </div>
                </div>
            </main>
        </div>
    </div>

{% endblock %}